### ISSUE TITLE
Expansão dos Requisitos - Gabriel

### ISSUE THREAD

**Issue by danieljunior** [Berna-L/Trabalho-ES2#1]
Especificar com detalhes o processo para atender os seguintes requisitos:
EMISSÃO DE CHEQUES
COMPENSAÇÃO DE CHEQUES
CONSTRUÇÃO DA VISUALIZAÇÃO DE SALDO

**Comment by gabcarrara** [comment]
**Compensação de Cheques**
1.O cliente deverá escolher a opção Depósito no menu so sistema;
2.O cliente deverá informar o valor do depósito que será feito;
3.O cliente deverá colocar o cheque em um envelope para depósito devidamente preenchido e assinalado como depósito em cheque;
4.O cliente deverá inserir o envelope no compartimento de depósitos do ATM;
5.O sistema deverá fazer a leitura do código de barras do envelope e registrar aquela operação na conta do cliente para aguardar a compensação física do cheque;
6.Feita a compensação física o sistema deverá creidater o saldo na conta do cliente.

 5.1.**Compensação física do cheque**
5.1.1.O sistema verifica se o cheque pertence ao mesmo banco em que ele foi depositado se for vá para o passo 2, caso contrário o sistema credita um saldo provisório que deverá ficar bloqueado por alguns dias e o cheque é enviado para a Câmara de compensação onde será repassado para seu devido Banco;
5.1.2. O Banco verifica a assinatura do cliente e o saldo da conta e se ambos estiverem em ordem o saldo é transferido para o Banco de quem depositou, caso contrário o cheque é devolvido para quem o enviou.

**Emissão de Cheques**
1.O Cliente deverá escolher a opção de emissão de cheques no menu do sistema;
2.O Cliente deverá informar a quantidade de folhas que deseja imprimir entre 4 e 20 folhas;
3.O sistema deverá imprimir os cheques com números de identificação únicos em cada um.

**Visualização do Saldo**
1.O cliente deverá escolher a opção de visualização de saldo no menu do sistema;
2.O cliente deverá escolher qual de suas contas deseja consultar;
3.O sistema deverá imprimir na tela o valor do saldo da conta escolhida.

**Comment by Berna-L** [comment]
Reaberto a pedido do Gabriel.
