### ISSUE TITLE
Expansão dos Requisitos - Diego

### ISSUE THREAD

**Issue by danieljunior** [Berna-L/Trabalho-ES2#2]
Especificar com detalhes o processo para atender os seguintes requisitos:
REALIZAÇÃO DE SAQUE
EXIBIÇÃO DE EXTRATO
CRIAÇÃO DO CRUD DE CLIENTES

**Comment by Diego13pa** [comment]
**1. CRIAÇÃO DO CRUD DE CLIENTES**

1.1. O sistema deve permitir a criação de um cliente como uma pessoa física ou jurídica
1.2. A criação de um cliente como pessoa física requer nome completo, endereço (rua, número, complemento), bairro, cidade, estado, cep, rg, data de emissão do rg, órgão emissor do rg, cpf, números de telefones, estado civil, e-mail (opcional), nome do cônjuge (opcional), local de trabalho (opcional), endereço comercial (opcional)
    1.2.1. Um cliente como pessoa física não pode ser criado sobre o mesmo cpf ou rg
    1.2.2. Os seguintes campos não podem sofrer update ou delete para pessoa física: nome completo, rg, data de emissão do rg, órgão emissor do rg, cpf
1.3. A criação de um cliente como pessoa jurídica requer nome completo, endereço (rua, número, complemento), bairro, cidade, estado, cep, telefones, e-mail, nome de fantasia, CNPJ ou inscrição estadual, tipo de empresa e data de fundação
    1.3.1. Um cliente como pessoa jurídica não pode ser criado sobre o mesmo nome completo, nome de fantasia, CNPJ ou inscrição estadual
    1.3.2. Os seguintes campos não podem sofrer update ou delete para pessoa jurídica: nome completo, CNPJ, inscrição estadual, data de fundação
1.4. Um cliente não pode ser criado sem apresentar, no mínimo, 1 número de telefone, e não deve sofrer update ou delete de modo que tenha um número de telefones menor que 1
1.5. Um cliente não pode ser deletado do sistema

**2. REALIZAÇÃO DE SAQUE**

2.1. O sistema deve operar apenas com notas de 10, 20, 50 e 100
2.2. O sistema deve informar quais as notas estão disponíveis atualmente
2.3. O sistema deve informar ao cliente que é impossível realizar um saque quando seu saldo for inferior ao menor valor de nota disponível
2.4. O sistema deve exibir na tela valores predefinidos de saque, baseados nas cédulas disponíveis em caixa e no saldo do cliente, e um campo "Outro:" onde o cliente possa digitar o valor a ser sacado
    2.4.1. Deve ser permitido ao cliente apenas digitar múltiplos de 10, e deve ser exibida a parte restante como "0,00"
2.4.2.  O sistema deve informar a impossibilidade do saque quando não há um número de cédulas disponíveis em caixa que satisfaça o valor digitado, ou quando o valor digitado for superior ao valor do seu saldo, ou quando o valor digitado for superior ao limite preestabelecido pelo tipo de conta e horário

**3. EXIBIÇÃO DE EXTRATO**

3.1. Deve ser disponibilizada a exibição do extrato na tela para movimentação diária
3.1.1. O cliente deve ser informado sobre a impossibilidade da exibição em tela quando o número de transações a ser exibida for superior ao máximo que pode ser exibido
3.2. O cliente deve escolher o período do extrato a ser impresso, informando o mês e o ano referente ao extrato
3.2.2. Uma taxa para a impressão do extrato deve ser informada ao cliente para períodos superiores a 1 mês
3.2.3. Haverá taxa a ser cobrada a partir do terceiro extrato no mês contendo a movimentação dos últimos 30 dias
3.3. O extrato deve exibir o nome do banco, a data de emissão, o nome completo do titular da conta, o número da agência do titular da conta, o número da conta, o período do extrato, o saldo anterior e para cada transação: sua data, tipo, número do documento, valor em crédito, valor em débito, saldo e descrição

**Comment by Diego13pa** [comment]
REALIZAÇÃO DE DEPÓSITO
1. O cliente não precisa estar logado para realizar esta operação
2. O cliente escolhe se o depósito será feito em uma conta corrente ou conta poupança
3. O cliente insere na tela os dados bancários do favorecido (agência, conta) e o valor a ser depoistado
4. Confirmação na tela dos dados do beneficiário
5. Inserção do envelope na máquina, com o valor a ser depositado
6. Confirmação do depósito
7. Imprimir o comprovante de depósito com o nome, agência e conta do beneficiário, o valor depositado e o número da transação
8. Um funcionário do banco retira o envelope e confere a transação. Se o valor estiver correto, ele dá o ok, senão, ele edita a transação com o valor que foi conferido no envelope.
9. Se o envelope foi colocado na máquina antes das 16h, o valor depositado entrará na conta do beneficiário no início do dia seguinte, senão, o valor cairá dois dias depois.
