### ISSUE TITLE
Expansão dos Requisitos - Romulo

### ISSUE THREAD

**Issue by danieljunior** [Berna-L/Trabalho-ES2#3]
Especificar com detalhes o processo para atender os seguintes requisitos:
CRIAÇÃO DO CRUD DE CONTAS
REALIZAÇÃO DE SAQUE
CONSTRUÇÃO DA AUTENTICAÇÃO DO CLIENTE

**Comment by romulo-martins** [comment]
<b>CRIAÇÃO DO CRUD DE CLIENTES</b>
1.  O sistema deve permitir o cadastro de clientes do banco, com todos os seus dados cadastrais.
2.  Para uma pessoa física os dados são: nome, sobrenome, endereço completo, telefones, e-mail, estado civil, nome do cônjuge, local de trabalho, endereço comercial, data de nascimento, CPF, RG, data de emissão e órgão emissor.
3.  Para uma pessoa jurídica os dados são: nome, sobrenome, endereço completo, telefones, e-mail, nome de fantasia, CGC ou inscrição estadual, tipo de empresa e data de fundação.
4.  O cliente após efetuar o cadastro não pode ter o saldo zero, ou seja, ele precisa depositar um valor mínimo.
5.  Ao ser cadastrado no sistema o cliente precisa ter pelo menos uma conta, sendo conta poupança ou conta corrente.
6.  Um cliente pode possuir várias contas no banco.

<b>REALIZAÇÃO DE SAQUE</b>
1.  O sistema deve pedir para o cliente efetuar o log-in antes de poder realizar a operação de saque. 
2.  O Sistema deve mostrar uma mensagem de erro caso o cliente informe um valor para saque que exceda o saldo + limite.
3.  O sistema deve informar para o usuário as notas que estão disponíveis no ATM naquele presente momento para realizar o saque no valor informado, por exemplo, se o cliente deseja retirar 20 reais o sistema mostra que ele pode tirar duas de 10 ou uma de 20.

<b>CONSTRUÇÃO DA AUTENTICAÇÃO DO CLIENTE</b>
1.  O sistema deve pedir o log-in e senha para autenticar o cliente.
2.  Se o cliente digitar a senha erradamente por três vezes consecutivas, o sistema trava a conta e o cliente deverá entrar em contato com sua agência no próximo dia útil.

**Comment by romulo-martins** [comment]
retirei alguns requisitos do saque que estavam idênticos ao do Diego
