### ISSUE TITLE
Expansão dos Requisitos - Bernardo

### ISSUE THREAD

**Issue by danieljunior** [Berna-L/Trabalho-ES2#4]
Especificar com detalhes o processo para atender os seguintes requisitos:
APLICAÇÃO EM INVESTIMENTOS
REALIZAÇÃO DE PAGAMENTOS
EFETUAÇÃO DE TRANSFERÊNCIA

**Comment by Berna-L** [comment]
_Expansão quase completa, ainda pesquisarei mais sobre investimentos, mas imagino que esse é o básico_

## Aplicação em investimentos
1. O sistema deverá exibir os tipos de investimentos disponíveis ao cliente.
2. O cliente deverá escolher um dos tipos de investimentos.
3. O cliente deverá informar o valor desejado para investir.
4. O sistema deverá exibir o rendimento estimado do valor informado ao mês e ao ano.
5. O cliente deverá ter a opção de informar uma data de cancelamento do investimento.
6. O sistema deverá, antes de confirmar a aplicação, exibir todos os dados ao cliente, solicitando confirmação explícita.
7. Após a confirmação explícita do cliente, o sistema deverá exibir o código de confirmação do investimento, além dos dados já exibidos.

## Realização de pagamentos
1. O cliente deverá informar qual tipo de pagamento será realizado:
   - Conta de concessionárias e empresas conveniadas (água, luz, telefone, etc.);
   - Boleto bancário.
2. O cliente deverá informar o código da conta ou boleto.
3. Caso o boleto não possua valor predefinido, o cliente deverá informar o valor do mesmo.
4. Caso o boleto não possua vencimento predefinido, o cliente deverá informar o vencimento do mesmo.
   - Caso o boleto esteja vencido, o sistema deverá impedir o pagamento, solicitando que o cliente vá a uma agência.
5. O cliente deverá ter a opção de informar um texto de até 15 caracteres (como "cartão amex") como descrição do pagamento no extrato.
6. O cliente deverá ter a opção de agendar o pagamento para uma data nos próximos 30 dias ou até o vencimento (o que vier antes).
7. O sistema deverá informar a data de realização do pagamento, **com destaque** se o cliente estiver realizando um pagamento imediato, mas após o expediente bancário.
8. O sistema deverá, antes de confirmar o pagamento, exibir todos os dados ao cliente, solicitando confirmação explícita.
9. Após a confirmação explícita do cliente, o sistema deverá exibir o código de confirmação do pagamento, além dos dados já exibidos.

## Efetuação de transferência
1. O cliente deverá informar a conta do favorecido de duas formas:
   - Informando agência, conta, CPF e Nome do favorecido;
   - Escolhendo o favorecido dentre uma lista de pré-cadastrados.
     - Caso informe um novo favorecido, o cliente deverá ter a opção de escolher adicioná-lo à lista de cadastrados.
2. O cliente deverá informar um valor entre R$ 0,01 e o valor disponível em sua conta para a transferência.
3. O cliente deverá ter a opção de informar um texto de até 15 caracteres (como "mesada filho") como descrição da transferência no extrato.
4. O cliente deverá ter a opção de agendar a transferência para uma data nos próximos 30 dias.
5. O sistema deverá informar a tarifa que será cobrada pela transferência, se houver.
6. O sistema deverá informar a data de realização da transferência, **com destaque** se o cliente estiver realizando uma transferência imediata, mas após o expediente bancário.
7. O sistema deverá, antes de confirmar a transferência, exibir todos os dados ao cliente, solicitando confirmação explícita.
8. Após a confirmação explícita do cliente, o sistema deverá exibir o código de confirmação da transferência, além dos dados já exibidos.
